### ISSUE TITLE
Backpack Dye Patterns Ineffective

### ISSUE THREAD

**Issue by Xechorizo** [Salandora/SophisticatedBackpacks#12]
Describe the bug
- Backpack dye recipes only work if dye is directly under the backpack. Other shapeless recipes are accepted but don't produce a dyed backpack, using up the dye anyway.
Crash log if it's a crash.
- NA
Info on what other mods you're using that may cause a conflict here if applicable.
- Created a dedicated Minecraft v1.20.1 Fabric v0.15.11 instance to replicate this.
Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

To Reproduce
- Open any crafting interface (inventory, table)
- Place Backpack (any tier)
- Place any dye around the backpack other than directly below the backpack.
- Retrieve the crafted "dyed" backpack
- Note the dye is not applied despite the dye being used.

Expected behavior
- Either all shapeless patterns to dye backpacks work to dye the backpack, or the only functional pattern (currently dye-under-backpack) is accepted.

Screenshots
- ![image](https://github.com/Salandora/SophisticatedBackpacks/assets/14857131/e91e65c9-aec5-4604-abcd-c07300c1ec76)

Versions
Mod version that you're using. Version of forge may also be helpful in some cases.
- fabric-api-0.92.1+1.20.1.jar
- ModernKeyBinding-Fabric-1.20-1.2.1.jar
- sophisticatedbackpacks-3.19.4+mc1.20.1-SNAPSHOT-build.39.jar
- sophisticatedcore-0.5.108+mc1.20.1-SNAPSHOT-build.39.jar

**Comment by Salandora** [comment]
So when you place the dye in the right sports of the crafting table it does dye the backpack but it only dyes the accessory stripes.
![image](https://github.com/Salandora/SophisticatedBackpacks/assets/2113125/c0378167-b819-4fc4-9384-23d18190be2e)

In the case of your image you started with red stripes and by adding cyan it went gray.

EDIT: Also checked against the forge version and it works the same there

**Comment by xechor** [comment]
Thank you! False report, closing.
