### ISSUE TITLE
Random crash with Iris shaders

### ISSUE THREAD

**Issue by HayLinIAmIn** [Salandora/SophisticatedBackpacks#15]
Minecraft crashes at random times (but very rarely). This happened when quickly descending into a dimly lit room and when quickly turning the camera 180 degrees.
[crash-2024-05-22_16.34.52-client.txt](https://github.com/Salandora/SophisticatedBackpacks/files/15404198/crash-2024-05-22_16.34.52-client.txt)

**Comment by Salandora** [comment]
Looked at this for the past 30 minutes or so just to now figure out I already fixed that issue 3 weeks ago 6402828
So will hopefully fixed in the upcoming bugfix release. 
Thanks for reporting.

**Comment by Salandora** [comment]
New release with bugfix on CF and Modrinth
