### ISSUE TITLE
Support for Fabric 0.91.0

### ISSUE THREAD

**Issue by supramaxis** [Salandora/SophisticatedBackpacks#16]
I was wondering if you could make this port work for Fabric 0.91.0 as that one version is used by the Prominence II modpack, and changing it breaks other mods compatibility, it would be so useful because i hate Travelers backpack, so i was trying to get an alternative, and found your port

![image for reference](https://github.com/Salandora/SophisticatedBackpacks/assets/88255405/5e4a1503-8b00-4600-a75b-cb5993c19302)

**Comment by Salandora** [comment]
Hello your Zenith version is from January.
From what I saw in their github repository they switched to fabric-api 0.92.1
So you could try to update Zenith.

**Comment by supramaxis** [comment]
Hey!, Thanks for finding that out, I'll update Zenith then
