### ISSUE TITLE
1.20.1 Hard crash when opening backpack with an Anvil Upgrade

### ISSUE THREAD

**Issue by FunglFun** [Salandora/SophisticatedBackpacks#18]
I've consistently been trying to use a backpack with an anvil upgrade but after a while the backpack seemingly enters a "bugged" state and hard crashes anyone who tries to open the backpack. While the backpack does not immediately become "bugged" overtime something causes it to become that way.
Fabric Mods: 
		amendments: Amendments 1.20-1.1.29
			mixinsquared: MixinSquared 0.1.1
		arc: Arc 1.6.2
		archers: Archers (RPG Series) 1.2.1+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		architectury: Architectury 9.2.14
		artifacts: Artifacts 9.5.5
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			expandability: ExpandAbility 9.0.4
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
		azurelibarmor: AzureLib Armor 2.0.3
		balm-fabric: Balm 7.2.2
		bellsandwhistles: Create: Bells & Whistles 0.4.5
		bettercombat: Better Combat 1.8.5+1.20.1
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.4
		betterendisland: YUNG's Better End Island 1.20-Fabric-2.0.6
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.6
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.5
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		biomemusic: Biome Music Mod 1.20.1-2.3
		biomespawnpoint: Biome Spawn Point 2.2
		bookshelf: Bookshelf 20.1.10
		brutes_dropscraps_mr: Brutes Drop Scraps 1.1
		citresewn: CIT Resewn 1.1.5+1.20.1
			citresewn-defaults: CIT Resewn: Defaults 1.1.5+1.20.1
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.4
		cobblemon: Cobblemon 1.5.0+1.20.1
		cobblemon_capturexp: Cobblemon Capture EXP 1.5-fabric-1.0.1
		cobblemon_spawn_notification: Cobblemon Spawn Notification 1.4-fabric-1.3.0
		cobblepedia: Cobblepedia 0.5.3
		collective: Collective 7.57
		continuity: Continuity 3.0.0-beta.5+1.20.1
		create: Create 0.5.1-f-build.1417+mc1.20.1
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_brewing: Porting Lib Brewing 2.3.2+1.20.1
			porting_lib_models: Porting Lib Models 2.3.2+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.2+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.2+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		create_cobblemon: Create: Cobblemon Industrialized 0.3
		create_dd: Create: Dreams & Desires 0.1d
			dsbg: Detected setBlock Be Gone 1.0
		createaddition: Create Crafts & Additions 1.2.3
		createfood: Create: Food 1.0.6
		cupboard: cupboard 1.20.1-2.6
		delightfulcreators: Delightful Creators 1.1.8
		enchdesc: EnchantmentDescriptions 17.0.14
		entity_model_features: Entity Model Features 2.0.2
		entity_texture_features: Entity Texture Features 6.0.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		expandeddelight: Expanded Delight 0.3.1
			omega-config: OmegaConfig 1.4.0+1.20.1
		experienced_crops: Experienced Crops 1.20.1-1.1.0
		fabric-api: Fabric API 0.92.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+1802ada577
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.10.20+kotlin.1.9.24
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.24
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.24
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.24
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.24
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.9
			mixinextras: MixinExtras 0.3.5
		fakerlib: fakerlib 0.1.3
		farmersdelight: Farmer's Delight 1.20.1-2.1.1+refabricated
			mm: Manningham Mills 2.3
			porting_lib_accessors: Porting Lib Accessors 2.3.4+1.20.1
			porting_lib_base: Porting Lib Base 2.3.4+1.20.1
				porting_lib_entity: Porting Lib Entity 2.3.4+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.4+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.4+1.20.1
				porting_lib_transfer: Porting Lib Transfer 2.3.4+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.4+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.4+1.20.1
				porting_lib_core: Porting Lib Core 2.3.4+1.20.1
			porting_lib_config: Porting Lib Config 2.3.4+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.4+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.4+1.20.1
				porting_lib_common: Porting Lib Common 2.3.4+1.20.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.4+1.20.1
			porting_lib_loot: Porting Lib Loot 2.3.4+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.4+1.20.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.3.4+1.20.1
			porting_lib_registries: Porting Lib Registries 2.3.4+1.20.1
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.4+1.20.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		gazebo: Gazebos 1.1.1+1.20.1
		iceberg: Iceberg 1.1.18
		indium: Indium 1.0.30+mc1.20.4
		interiors: Create: Interiors 0.5.3+fabric-mc1.20.1
		iris: Iris 1.7.0+mc1.20.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		irisflw: Iris Flywheel Compat 0.2.5
		ironchests: Iron Chests: Restocked 5.0.2
			resourcefullib: Resourceful Lib 2.0.6
				com_teamresourceful_yabn: yabn 1.0.3
		itemrestrictions: Item Restrictions 1.2
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.3.0.4
		jeresources: Just Enough Resources 1.4.0.247
		jewelry: Jewelry (RPG Series) 1.3.0+1.20.1
		jobsplus: Jobs+ 1.3.7
		legendarytooltips: Legendary Tooltips 1.4.5
		letmedespawn: Let Me Despawn 1.2.0
		megamons: Ascension Megamons 1.5.0+1.20.1-forge+fabric-75b66fa
		minecraft: Minecraft 1.20.1
		mkb: ModernKeyBinding 1.2.1
		modmenu: Mod Menu 7.2.2
		moonlight: Moonlight 1.20-2.11.20
		mr_banner_flags: Banner Flags 2.3
		mr_dungeons_andtaverns: Dungeons and Taverns 3.0.3.f
		mr_tool_trims: Tool Trims 2.0.2+1.20
		naturescompass: Nature's Compass 1.20.1-2.2.3-fabric
		paladins: Paladins & Priests (RPG Series) 1.2.0+1.20.1
		patchouli: Patchouli 1.20.1-84-FABRIC
			fiber: fiber 0.23.0-2
		player-animator: Player Animator 1.0.2-rc1+1.20
		prism: Prism 1.0.5
		railways: Create: Steam 'n' Rails 1.6.4+fabric-mc1.20.1
		ranged_weapon_api: RangedWeaponAPI 1.1.1+1.20.1
		runes: Runes 0.9.11+1.20.1
		seasons: Fabric Seasons 2.3+1.20
		seasonsdelightcompat: Fabric Seasons: Delight Compat 1.0-1.3.9
		seasonsextras: Fabric Seasons: Extras 1.2-BETA+1.20
		seasonsterralithcompat: Fabric Seasons: Terralith Compat 1.0-2.3.7
		sodium: Sodium 0.5.8+mc1.20.1
		sophisticatedbackpacks: Sophisticated Backpacks 3.19.4+mc1.20.1-build.39
			team_reborn_energy: Energy 3.0.0
		sophisticatedcore: Sophisticated Core 0.5.108+mc1.20.1-build.39
		sophisticatedstorage: Sophisticated Storage 0.8.59+mc1.20.1-build.39
		spell_engine: Spell Engine 0.14.3+1.20.1
		spell_power: Spell Power Attribute 0.10.2+1.20.1
		structure_pool_api: Structure Pool API 1.0+1.20.1
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supplementaries: Supplementaries 1.20-2.8.11
		tectonic: Tectonic 2.3.4
		terralith: Terralith 2.5.1
		toms_storage: Tom's Simple Storage Mod 1.6.6
		trinkets: Trinkets 3.7.2
		uilib: UI Lib 0.3.5
		waystones: Waystones 14.1.3
		wizards: Wizards (RPG Series) 1.2.0+1.20.1
		xaerominimap: Xaero's Minimap 24.1.1
		xaeroworldmap: Xaero's World Map 1.38.4
		yungsapi: YUNG's API 1.20-Fabric-4.0.5
			org_javassist_javassist: javassist 3.29.2-GA
		yungsbridges: YUNG's Bridges 1.20-Fabric-4.0.3

Steps to reproduce the crash:
1. Open backpack
2. Insert Anvil Upgrade into backpack
3. Some time passes
4. Attempt to open backpack
5. java.lang.StackOverflowError: Unexpected error at net.p3pp3rf1y.sophisticatedbackpacks.upgrades.anvil.AnvilUpgradeContainer$PersistableAnvilMenu.getItemName(AnvilUpgradeContainer.java:100)

**Comment by Salandora** [comment]
Hi yes unfortunately it's a known bug (#11) and fixed in dev.
The update was supposed to be out already but more bugs and crashes appeared which is why it is a bit delayed.

**Comment by Salandora** [comment]
New release with bugfix on CF and Modrinth
