### ISSUE TITLE
Game crashes after launching it with the 1.19.2 version of the mod

### ISSUE THREAD

**Issue by iDivin** [Salandora/SophisticatedBackpacks#2]
Crash log:
https://pastebin.com/f94gCryN

It crashes when I try to enter my world, which results in a freeze and a black screen right before being able to play. 

I set the fabric loader in the fabric.mod.json to 0.14.22

**Comment by Salandora** [comment]
Issue was resolved in Discord.
Wasn't related to Backpacks but another mod and it's dependencies.
