### ISSUE TITLE
anvil upgrade causing crashes when books are left inside when exiting bag

### ISSUE THREAD

**Issue by iGuessImWill** [Salandora/SophisticatedBackpacks#20]
the steps in recreating this are as follows

Add an Anvil Upgrade in the Netherite Backpack.
Add two enchanted books in the anvil config inside the Netherite Backpack.
Close the inventory menu of the Netherite Backpack.
Try to open the Netherite Backpack again.
Client crashes and Exit Code: 255 shows up.
---- Minecraft Crash Report ----
as far as i can see it happens in both multi and single player,

[New Compressed (zipped) Folder.zip](https://github.com/Salandora/SophisticatedBackpacks/files/15446461/New.Compressed.zipped.Folder.zip)

**Comment by Salandora** [comment]
Please update the mods there if a fix for that in the newest update.
