### ISSUE TITLE
Modern Keybinding causing Problems with AMECS mod. Fabric 1.20.1

### ISSUE THREAD

**Issue by Hexblood** [Salandora/SophisticatedBackpacks#21]
**Describe the bug**

With both AMECS and Modern Keybinding you can no longer assign Modifier keys in your keybinds. I have reported to both MKB and AMECS devs but thought you should know as well. MKB has not been updated in almost a year and has not responded to issues on their github in several months. 

AMECS normally allows modifier keys so if that is what you are looking for in MKB then it may not be necessary to use that mod as a 
hard dependency.

**To Reproduce**
1. Install both AMECS and Modern Keybinding.
2. attempt to set a keybind with a modifier key.
3. only the last key pressed in the set will be applied

**Expected behavior**
The ability to set keybinds with modifiers.

**Versions**
MC 1.20.1
Modern Keybinding Fabric-1.20.X-1.2.0
AMECS 1.3.10+mc.1.20.1
Fabric 0.15.11
Fabric API 0.92.2+1.20.1

**Comment by Salandora** [comment]
Hi,

yeah I'm aware that AMECS and ModernKeybinding do not play well together. 

With the next big update I want to look into the keybinding again and check if I can get around the hard dependency.
Currently even on servers you would need mkb (#17) or manually edit the jar or use a dependency override.
So this is another good reason to revisit keybindings.

**Comment by Hexblood** [comment]
Thank you for taking a look at this. I very much want to use the Sophisticated mods in my packs but a conflict like this is kind of a deal breaker for me. I will keep an eye out for the update.

**Comment by Salandora** [comment]
Modern KeyBinding is no longer a required dependency
