### ISSUE TITLE
Issue with build.gradle

### ISSUE THREAD

**Issue by jtd023** [Salandora/SophisticatedBackpacks#22]
**Branch: 1.20.1-fabric-dev**

**Description:**
I am encountering an issue when trying to build the project. The build fails with the following error:

```
FAILURE: Build failed with an exception.

* Where:
Build file 'A:\Local\SophisticatedBackpacks\build.gradle' line: 1

* What went wrong:
A problem occurred evaluating root project 'SophisticatedBackpacks'.
> Could not find method moduleDependency() for arguments [root project 'SophisticatedBackpacks', [SophisticatedCore]] on root project 'SophisticatedBackpacks' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 22s
```

**Steps to Reproduce:**

1. Clone the repository.
2. Run ./gradlew build.

I've tried different configurations but keep encountering this issue. Any guidance or assistance would be greatly appreciated. Additionally, if possible, could you please provide the pre-built .jar file for the mod? This would help me use the mod without needing to troubleshoot the build process further. Thank you!

**Comment by Salandora** [comment]
For compiling you shoukd use the SophisticatedMods repository, this repository here serves as a module for it.

I probably should document that in the readme tbh.

In the same repo you'll find pre built jars under the actions tab.
If you want more stable files you can get them from curseforge or modrinth.

**Comment by jtd023** [comment]
Thanks!
