### ISSUE TITLE
java.lang.RuntimeException: We are asking a region for a chunk out of bound

### ISSUE THREAD

**Issue by McBlob** [Salandora/SophisticatedBackpacks#24]
java.lang.RuntimeException: We are asking a region for a chunk out of bound

**To Reproduce**
Load structure from repurposed structures
skeleton with backpack spawn
crash
[crash-2024-06-16_17.15.52-server.txt](https://github.com/user-attachments/files/15858904/crash-2024-06-16_17.15.52-server.txt)

**Versions**
1.20.1 fabric

I don't know anything about minecraft modding but i think it has something to do with the spawning of skeletons in the dungeon and the spawning of skeletons with backpacks or something. This was a huge modpack so it also could be something else

**Comment by Salandora** [comment]
Yeah you're absolutely correct.
I'll fix the bug in the upcoming major feature update.

Until then you can set **entityBackpackAdditions equipWithArmor** to false in the sophisticatedbackpacks-server.toml
This will prevent skeletons from spawning with Armor pieces in addition to backpacks. (Which is the part that crashes your game)

**Comment by McBlob** [comment]
Changing the config fixed the crash. Thanks!

**Comment by Salandora** [comment]
I would like to keep the bug report open for now cause the actual bug is not yet fixed.
This helps keeping track of what I still need to fix for the next release.

**Comment by Salandora** [comment]
Fix is out.
