### ISSUE TITLE
The plus symbol appears.

### ISSUE THREAD

**Issue by Shadowbee27** [Salandora/SophisticatedBackpacks#26]
When holding an item the + symbol from the backpack on the Back slot appears.
1. Put Backpack in the Back slot
2. Go into survival
3. Click on a item 
4. The + symbol appears

![Screenshot 2024-06-21 194624](https://github.com/Salandora/SophisticatedBackpacks/assets/169397554/d7022aa0-9127-4e49-a5a2-abef39a5138e)

**Comment by Salandora** [comment]
Fixed in sophisticatedcores dev-feature-update

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
