### ISSUE TITLE
placed Backpack does not open 

### ISSUE THREAD

**Issue by Shadowbee27** [Salandora/SophisticatedBackpacks#28]
A placed Backpack does not open when clicked with a bukkit after disabling simple place mode in litematica.

https://github.com/Salandora/SophisticatedBackpacks/assets/169397554/f4c167c8-08f5-4d17-82a9-8a92a70c1594

**Comment by Salandora** [comment]
This is actually the same in the forge version.
If you add a tank upgrade to it you can put water in the tank and pull from it like this.

**Comment by Shadowbee27** [comment]
ok thanks
