### ISSUE TITLE
Incompatibility with accessories mod

### ISSUE THREAD

**Issue by ChosenMark** [Salandora/SophisticatedBackpacks#29]
https://www.curseforge.com/minecraft/mc-mods/accessories
not working with this mod installed

**Comment by Salandora** [comment]
Can you try the currently released Accessories and Trinket Compats Layer for Accessories.

**Comment by Salandora** [comment]
Fixed in accessories trinket compats layer and fixed in dev-feature-update as there is the correct validation now.

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
