### ISSUE TITLE
[1.20.1] Opening a generating chest will make the server crash on a StackOverflow

### ISSUE THREAD

**Issue by busybox11** [Salandora/SophisticatedBackpacks#3]
**Describe the bug**
Using the 1.20.1 port preview, opening a not yet generated chest will make the server crash, reporting a StackOverflowError with the message "null". Stack trace attached.

[sophisticatedBackpacks_log_20240426.log](https://github.com/Salandora/SophisticatedBackpacks/files/15123658/sophisticatedBackpacks_log_20240426.log)

This has been manually compiled from source using your fork, without any modifications.

I don't have the time to take a look at the code yet, but I would happily try to debug this with you, or provide assistance if needed. We are testing your amazing fork because of performance issues with our former Forge server, that's the reason we are switching to Fabric.

We are very grateful of your work regardless and I thank you a lot for making this mod accessible on Fabric. We probably couldn't continue hosting our Minecraft server if it was not for your work. Can't wait to see it released.

**Comment by Salandora** [comment]
Thank you for reporting this issue.
It's fixed now.
Really hope the switch to fabric saves your server, good luck!
