### ISSUE TITLE
EMI Compatibility

### ISSUE THREAD

**Issue by Greazi-Times** [Salandora/SophisticatedBackpacks#37]
**Describe the bug**
When I am trying to craft items using the [EMI](https://github.com/emilyploszaj/emi) mod it doesn't allow me to craft them if the items are memorized in a slot resulting in giving an item not found message/error (not an actual error). See images for more information.

**To Reproduce**
1. Get a Backpack
2. Put items in the backpack
3. Open the settings and memorize the items at that position
4. Try to make a recipe that require these items which are memorized

**Expected behavior**
To be able to craft the recipes,

**Screenshots**
![afbeelding](https://github.com/user-attachments/assets/4b8e5402-d476-4edb-8146-6a5a4d5b92c5)
*Grayed-out items are memorised*

![afbeelding](https://github.com/user-attachments/assets/9749863c-1dc6-4424-920d-0322bb7d19b0)
![afbeelding](https://github.com/user-attachments/assets/ab476898-6498-4f39-bb8d-86d117b525b8)

As shown in the images I have 282 Spruce planks and 193 Andesite Alloys (2 items to the right of the gold ingots) but I am unable to craft these items. When I disable the item memory I can craft the things.

**Versions**
EMI Version: v1.1.10+1.20.1+fabric
Sophisticated Backpacks: V3.19.5+mc1.20.1-SNAPSHOT-build.104
Server version: 1.20.1

**Comment by Greazi-Times** [comment]
I have created an issue with EMI as well please see the post there as well: https://github.com/emilyploszaj/emi/issues/635
*As I am not sure which mod causes this issue*

**Comment by Salandora** [comment]
Hmm can you check if it works if you don't memorize them but set them as "no sort"?

I know no sort is working for me and I thought I used it with memorized slots too but I might have never done that....

**Comment by Greazi-Times** [comment]
> Hmm can you check if it works if you don't memorize them but set them as "no sort"?
> 
> I know no sort is working for me and I thought I used it with memorized slots too but I might have never done that....

Hi, thank you for your reply,
Just tried it and no it doesn't seem to work either.

![afbeelding](https://github.com/user-attachments/assets/6d9ccc49-c81e-432c-a55a-f070f255b11a)
![afbeelding](https://github.com/user-attachments/assets/15855841-89e0-446d-8d36-7139b023f044)
*Red markings mean no sorting*

**Comment by Salandora** [comment]
Hmm that is really strange.
Does it work without memorize and no sort?
What other mods do you have can you post a latest log please.

**Comment by Salandora** [comment]
Okay I was finally able to test things and ohh my... not only can I reproduce the issue but also found a dupe bug.

**Comment by Salandora** [comment]
Fixed in sophisticatedcores dev-feature-update

**Comment by Greazi-Times** [comment]
> Fixed in sophisticatedcores dev-feature-update

So this will be fixed in the next update of the mod?
And when will this update be published?

**Comment by Salandora** [comment]
Yes, I got some more reports in that I want to investigate before release but we are close to a release

**Comment by Greazi-Times** [comment]
Oke great thank you!
