### ISSUE TITLE
Crash between Sophisticated Backpacks/Storage and Chipped for Fabric 1.20.1

### ISSUE THREAD

**Issue by QueenDiancieTTV** [Salandora/SophisticatedBackpacks#39]
**Describe the bug**
Alright so theres a bug with the compat between chipped and soph backpacks/storage that was fixed back in February on the og forge version of the mod

[https://mclo.gs/HjhhWIO](url)

Shown here [Issue](https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/958)

The fixed forge version is sophisticated backpacks 3.19.8

**To Reproduce**
install both chipped and soph backpacks/storage

**Versions**
Fabric 1.20.1

**Comment by QueenDiancieTTV** [comment]
it causes crashes and i was just wondering if that bug could be fixed

**Comment by Salandora** [comment]
Try to update your chipped version you're running 3.0.1. The changes and bug you're refering to should have been introduced in 3.0.2.

**Comment by Salandora** [comment]
Closing as there is no response to this, so assuming the problem is solved
