### ISSUE TITLE
dont hate me :(

### ISSUE THREAD

**Issue by DesuPinkgit** [Salandora/SophisticatedBackpacks#42]
Im sure you get a lot of these but wanted to request it anyway. Its another version request. Basically I am hosting a medieval minecraft server for me and a bunch of friends and there is a lot of request for this mod as we all moved from forge after its implosion. The server is on 1.19.2 however the correct version of fabric loader of the server is 0.14.24. Could you give guidance on how i could change this myself or alternatively do a version with support for older versions of fabric loader . ( including sophisticated core ) . This is for the unofficial port to fabric btw since im not sure if this is the support for the og mod or port. thank you <3

**Comment by Shadowbee27** [comment]
@DesuPinkgit Why do you have to use 1.19.2 instead of 1.19.4

**Comment by DesuPinkgit** [comment]
> @DesuPinkgit Why do you have to use 1.19.2 instead of 1.19.4

@Shadowbee27
Medieval mc is a modpack and as far as i know a large portion of those still havent been updated and im not sure if there original modpack devs are going to be updating it anymore

**Comment by Shadowbee27** [comment]
@DesuPinkgit can you sent me a link to the modpack

**Comment by DesuPinkgit** [comment]
@Shadowbee27

https://www.curseforge.com/minecraft/modpacks/medieval-mc-fabric-mmc1

**Comment by Shadowbee27** [comment]
I had to remove a lot of mods in 1.19.4 and couldn't get it to work but now I am trying 1.20.1 @DesuPinkgit

**Comment by DesuPinkgit** [comment]
@Shadowbee27 im a tad lost , is that in response to the mod working with the modpack in 1.19.2 or just that there were issues with 1.19.4? additionally would any of the versions for 1.19.2 run on fabric loader 0.14.24?

**Comment by Shadowbee27** [comment]
@DesuPinkgit the modpack always crashed and I have no idea why but I am trying to get it working in 1.20.1

**Comment by Shadowbee27** [comment]
For 1.20.1 I had to remove Xp Obelisk, Wondrous Wilds but  I replace it with tectonic and teralith, straw golems, Whisperwods, charmfixer, Architech's Palette [Fabric]
and replaced data attributes with and updated fork
@DesuPinkgit  which launcher are you using

**Comment by DesuPinkgit** [comment]
@Shadowbee27 i am using Atlauncher

**Comment by Shadowbee27** [comment]
I have no Idea why but geckolib seems to have problems 
![2024-08-10_20-22](https://github.com/user-attachments/assets/092c50c4-a1b9-47a1-b62c-cba606aee797)
@DesuPinkgit

**Comment by Shadowbee27** [comment]
also had to remove [Redirector](https://www.curseforge.com/projects/877289)
and I am stuck with this error 
[22:05:27] [main/ERROR]:
 Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchFieldError: field_25108
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:482) ~[fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.0.jar:?]
Caused by: java.lang.NoSuchFieldError: field_25108
	at net.minecraft.class_1767.handler$gbk000$forge_tags$addTag(class_1767.java:529) ~[client-intermediary.jar:?]
	at net.minecraft.class_1767.<init>(class_1767.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_1767.<clinit>(class_1767.java:15) ~[client-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:247) ~[client-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[1.20.1-0.16.0.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.0.jar:?]
	... 2 more

**Comment by DesuPinkgit** [comment]
@Shadowbee27 what version of gecko lib is installed ?

**Comment by Shadowbee27** [comment]
@DesuPinkgit yes but the mods were outdated and didn't recognise the new version of geckolib so I had to remove all except Naturalist

**Comment by Shadowbee27** [comment]
@DesuPinkgit I will try to make the modpack working but it always crashes if you want to be updated jion the sophisticated Discord

**Comment by Shadowbee27** [comment]
@DesuPinkgit why don't you use the newer version of the modpack for 1.20.1

**Comment by DesuPinkgit** [comment]
@Shadowbee27 At the time of starting that was the most polished version with all that mods that people wanted. Never thought about updating to the new one tbh since I wasnt sure if every single thing would just work but switching

**Comment by Shadowbee27** [comment]
@DesuPinkgit I can understand you, currently I have no idea why the modpack isn't working and I am close to give up but I will try for some more time

**Comment by Shadowbee27** [comment]
@DesuPinkgit bad new the mods don't, if I leave it on 1.19.2 I am giving up if you want the modpack that doesn't start reply on this

**Comment by Salandora** [comment]
Okay so let me get this clear you need a version of Sophisticated Core & Backpacks that runs with fabric launcher 0.14.24 for MC 1.19.2?

You could try to download the 1.19.2 version from curseforge and open the jar files with a zip program.
Then find the fabric.mod.json and open it with an editor.
In that file you look for a similar line to this:
`"fabricloader": ">=0.15.7"`
and there you change the 0.15.7 to 0.14.24.

**Comment by DesuPinkgit** [comment]
@Shadowbee27 This seemingly works like a charm! opened it up so far no issues at all.  As a small sidenote though, if i wanted to change the texture. (just the one that shows on the character in third person or to others) ( for personal use of course ) . Would it be as simple as inserting a png or would it be far more complex? If it would be that simple which file would i need to replace? If its not that simple not to worry and thank you for the solution <3

**Comment by Shadowbee27** [comment]
I am not a java developer I learn Rust, but I would say you should be able to replace the .png

**Comment by DesuPinkgit** [comment]
ill give it a shot and play around, thank you for the super easy solution though <3
