### ISSUE TITLE
Particles missing and player skin went a bit weird

### ISSUE THREAD

**Issue by DesuPinkgit** [Salandora/SophisticatedBackpacks#43]
So I am using this on 1.19.2 with fabric loader version 0.14.24. I had to edit the fabric.json to have it work on that fabric loader version. When I was playing the medieval minecraft modpack without the and sophisticated core it was completely fine. Once adding i immediately started noticing a few things wrong. Particle effects from breaking blocks were completely gone ( very noticeable with fast breaking speeds such as creative) and my character skin started having some issues , The arms went really large and the torso had some weird colours on. Removing the mods everything instantly returned back to normal. I did however try it without changing the file and using the updated fabric loader on a completely clean fabric installation with no mods aside from the api and the issue is still there ( atleast the particles being missing when breaking blocks)

**Versions**
sophisticatedbackpacks-3.19.5+mc1.19.2-SNAPSHOT-build.103.jar + latest sophisticated core for 1.19.2

**Comment by Salandora** [comment]
I have a report for this in https://github.com/Salandora/SophisticatedCore/issues/7

The player model being affected is new tho, can you make a screenshot of it? 
I'll look into the block breaking particle problem.

**Comment by DesuPinkgit** [comment]
False alarm with the skin being bugged out , Was an issue being caused by an oversite on my part . Nothing to do with the backpack!

**Comment by Salandora** [comment]
Okay no problem.

In that case let's close this issue in favor of the one in the right repository ;) (if it is on my end then it's a bug in sophisticated core)
