### ISSUE TITLE
IBE Editor Incompatibility

### ISSUE THREAD

**Issue by programaus** [Salandora/SophisticatedBackpacks#45]
Issue:
- Sophiscated backpacks breaks [ibe editor](https://modrinth.com/mod/ibe-editor)'s editor slot targetting

Replication:
- Create a world
- Switch to creative
- Press I on any item in your **hotbar** (default keybind)
- Result: Selected item is minecraft:air (editing item to be anything other does not make it appear anywhere, even when checked trough nbt, so it seems like it targets a non-existent slot)
- Extra: 6th hotbar slot seems to target helmet, 7th hotbar is body, 8th hotbar is legs, and 9th hotbar is feet. All other hotbar slots target nothing.

Only happens in creative mode.
Only happens in inventory tab, doing the same actions inside a chest, crafting table, furnace gui will work fine without this issue

Fabric 1.20.1 0.16.5
all mods and their versions:
![image](https://github.com/user-attachments/assets/986ad735-5c67-47be-a161-2d45d4fbbf9f)

**Comment by Salandora** [comment]
Can confirm this as a bug.

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
