### ISSUE TITLE
Backpack dropping normally instead of with the Universal Graves mod when attached to back trinket slot.

### ISSUE THREAD

**Issue by MikaelArtiola** [Salandora/SophisticatedBackpacks#46]
When dying when using a gravestone mod, specifically Universal Graves https://modrinth.com/mod/universal-graves. (v. 3.0.3+1.20.1)
and Trinkets https://modrinth.com/mod/trinkets (v. 3.7.2)
Having the backpack equipped in the back slot while dying drops it normally on the ground for it to get burnt by lava or blown up.

Reproduced by:
1. Installing Universal Graves, trinkets and Sophisticated backpacks.
2. Equipping a backpack on you back slot.
3. Die
4. Backpack not being out in grave properly.

Expected behaviour would be in my mind that it puts the backpack in the inventory like other trinkets.

**Versions**
Universal Graves v. 3.0.3+1.20.1
Trinkets v. 3.7.2
Sophisticated Core 0.5.109+mc1.20.1-build.104
Sophisticated Backpacks 3.19.5+mc1.20.1-build.104

**Comment by Shadowbee27** [comment]
This could be because the grave mod does not support Trinkets

**Comment by MikaelArtiola** [comment]
It works fine with other items that use trinket slots.
For example Create's goggles and jetpack.

**Comment by Salandora** [comment]
Tested this and can't reproduce in current fabric-dev-feature-update branch.
I know there was another grave mod that also had issues with backpacks and I did fix something with the trinkets integration so it's likely this is fixed through that change too.

**Comment by MikaelArtiola** [comment]
> Tested this and can't reproduce in current fabric-dev-feature-update branch. I know there was another grave mod that also had issues with backpacks and I did fix something with the trinkets integration so it's likely this is fixed through that change too.

Okay cool! So is this something I should update, update fabric or trinkets? Although I have the latest for 1.20.1 :/

**Comment by Shadowbee27** [comment]
Just try to update everthing want you but considder taking a back-up of all importend worlds

**Comment by Salandora** [comment]
The update in question is not yet released, it's in the testing phase

**Comment by Shadowbee27** [comment]
I thought that he had not everthing updated

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
