### ISSUE TITLE
1.21.x support？

### ISSUE THREAD

**Issue by swe3per** [Salandora/SophisticatedBackpacks#47]
First of all, this is the best backpack mod I have ever used since I started playing Minecraft. 

It has a beautiful UI, simple functions, strong scalability, and is very compatible with many adventure and technology mods. 
Recently, the server has been upgraded to 1.21.1, and the official backpack has also been upgraded synchronously. Is there any upgrade plan for the fabric port?

**Comment by Salandora** [comment]
Yes I do plan to update to 1.21.
