### ISSUE TITLE
Crash when using JEI fill in grid feature (the "+" button) with crafting upgrade

### ISSUE THREAD

**Issue by DaveTheMagicalKidWizard** [Salandora/SophisticatedBackpacks#50]
While playing survival on a fabric mod pack made by me I wanted to use the crafting in my backpack. When I found the recipe in JEI I pressed on the "+" button to fill in the crafting recipe for me and it crashed.

1. Open backpack
2. Use JEI to auto fill the crafting grid from crafting upgrade
3. Crash

I was using fabric 0.16.5 on Minecraft 1.20.1, sophisticated core 0.5.109 and sophisticated backpacks 3.19.5
[crash-2024-10-09_17.18.58-client.txt](https://github.com/user-attachments/files/17311218/crash-2024-10-09_17.18.58-client.txt)

**Comment by Shadowbee27** [comment]
@DaveTheMagicalKidWizard This seems to be a sophisticated core problem

**Comment by Salandora** [comment]
Jei is to new there were some changes around jei 15.19... this is currently fixed in dev.

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
