### ISSUE TITLE
BeansBackpacks + Trinkets + keepInventory = Dropped Backpacks

### ISSUE THREAD

**Issue by GoldenFurredFox** [Salandora/SophisticatedBackpacks#54]
**Describe the bug**
When using BeansBackpacks and Trinkets, you will drop your backpack on death while the gamerule keepInventory is set to true.
Other mods I'm using are Trinkets version 3.7.2 by Emi and C4 [link](<https://www.curseforge.com/projects/341284>) and BeansBackpacks version 2.0.2 by BeansGalaxy [link](<https://modrinth.com/mod/kYt0MSgT>)

**To Reproduce**
1. Have both BeansBackpacks and Trinkets installed alongside Sophisticated Backpacks' and Sophisticated Core's Fabric ports.
2. Change the gamerule keepInventory to true.
3. Run the kill command or otherwise die.
4. Your backpack drops on the ground as though the gamerule wasn't changed, but the rest of your inventory remains.

**Expected behavior**
I expected my backpack to stay in the correct slot.

**Versions**
Sophisticated Backpacks: 3.19.5+mc1.20.1-SNAPSHOT-build.104 [link](<https://modrinth.com/mod/ouNrBQtq>)
Sophisticated Core: 0.5.109+mc1.20.1-SNAPSHOT-build.104 [link](<https://modrinth.com/mod/9jxwkYQL>)

This was also posted in P3pperfly's Discord. You can find the post [here](https://discord.com/channels/810643286511190016/1293453049515212811/1293453049515212811) if you're also in the server. If you're not, the link won't work for you.

**Comment by Shadowbee27** [comment]
@SamHammie This seems like a Beans Backpack problem because the beans backpack is being dropped or does it only happen when sophisticated Backpack is installed

**Comment by GoldenFurredFox** [comment]
@Shadowbee27 It happens with the Sophisticated Backpack in the Trinkets back slot. I haven't even checked if it happens with just BeansBackpacks and Trinkets, but I'd assume that it wouldn't since BeansBackpacks has compatibility with Trinkets by default.

**Comment by Shadowbee27** [comment]
@SamHammie try removing sophisticated Backpack and test it in a new world

**Comment by Salandora** [comment]
So first of all, sophisticated backpacks has trinket support too and with keepInventory set to true it is not dropping the backpack without BeansBackpacks when in the trinkets back slot.

Second:
BeansBackpacks introduced their own gamerule "/beansmod gamerule keepBackSlot" and a custom drop function https://github.com/BeansGalaxy/Beans-Backpacks-2/blob/20.1/common/src/main/java/com/beansgalaxy/backpacks/data/BackData.java#L213
The drop function checks if the item to be dropped is NOT a Beans Backpack and drops it if it is not https://github.com/BeansGalaxy/Beans-Backpacks-2/blob/20.1/common/src/main/java/com/beansgalaxy/backpacks/data/BackData.java#L239

So simply said BeansBackpack bypasses the keepInventory rule just for the back slot to use their own rule instead
and drops anything else regardless of the keepInventory rule.
While there is a way to "opt-out" of this I think either their code should respect the keepInventory rule
or this change should be an "opt-in" instead.

So for you this means you can use `/beansmod gamerule keepBackSlot true` to keep your backpack in case of a death.
