### ISSUE TITLE
[FABRIC VER] Inception Upgrade does not work in latest versions.

### ISSUE THREAD

**Issue by DonTomasDeLaVega** [Salandora/SophisticatedBackpacks#57]
**Describe the bug**
When pressing B on a backpack inside a backpack, instead of opening the secondary backpack, it just closes the first one.

**To Reproduce**
1. Have the latest versions of the mod to date (20 of october 2024)
2. Create a creative world, give yourself a few backpacks and the inception upgrade.
3. Put the inception in the main bp
4. Put the other bp inside
5. Press b with your mouth cursor on it

**Expected behavior**
Pressing B on a backpack inside the main backpack should open it.

**Versions**
Fabric : 1.20.1 loaderver 0.16.5

**Comment by Salandora** [comment]
New Sophisticated Core and Storage are out and should fix the issue.
