### ISSUE TITLE
Stacking upgarde dupe

### ISSUE THREAD

**Issue by Shadowbee27** [Salandora/SophisticatedBackpacks#58]
If the stack size is over the 64 in the case of cobblestone, if you put it direktly into the offhand the items are getting duped

[Video](https://github.com/user-attachments/assets/cd8b84c1-487b-4a59-ae9a-7131cdc9b423)

**Comment by Salandora** [comment]
That's weird, I tried reproducing it in my dev environment and it's working correctly there.
What versions are you on?

**Comment by Shadowbee27** [comment]
1.20.1-3.20.11.26 backpack 
1.20.1-0.6.33.31 core
Fabric 0.16.7

**Comment by Shadowbee27** [comment]
[Modpack](https://www.mediafire.com/file/cxh0tb59h4zvj90/Modpack.mrpack/file)

**Comment by Salandora** [comment]
No clue what mod could be causing this, if you find out let me know and I can look into what is causing it.

**Comment by Shadowbee27** [comment]
I still have no clue why it happened but after updating all mods the dupe does not work anymore
