### ISSUE TITLE
Ticking Entity

### ISSUE THREAD

**Issue by VoidPulsed** [Salandora/SophisticatedBackpacks#59]
**Describe the bug**
https://mclo.gs/daoq3Fa

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
I heard a backpack disc playing from a zombie, then found it and tried killing it, once I did. It crashed with this log. Now I can't log back into this world. 

**Expected behavior**
I wanna log back in with my backpacks. 

**Versions**
1.20.4 aka 3.20.6.30 (port) & 0.6.26.40 (ported core)

**Comment by VoidPulsed** [comment]
I went onto a different world, killed a zombie with a backpack and it ended up crashing my game again. Please fix or tell how to fix !

**Comment by Salandora** [comment]
Fixed in new version
