### ISSUE TITLE
disconnect

### ISSUE THREAD

**Issue by york626** [Salandora/SophisticatedBackpacks#66]
When I use Litematica-Fabric-1.21-0.19.51 and Exquisite Backpack-1.21.1-3.20.19.44
When opening the projection material list
Network connection failure occurred
Disconnect -2022-11-15_20.40.57-Client
Is there any good solution

[disconnect-2024-11-15_20.40.57-client.txt](https://github.com/user-attachments/files/17775699/disconnect-2024-11-15_20.40.57-client.txt)
![QQ20241115-210608](https://github.com/user-attachments/assets/93a90196-3c90-4da9-99a7-2d8f0b19281a)

**Comment by Salandora** [comment]
Exquisite Backpack? 

I'll look into it it's cause by my litematica compat.

**Comment by york626** [comment]
extremely grateful








Ray
***@***.***


---Original---
From: ***@***.***&gt;
Date: Sat, Nov 16, 2024 06:29 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Salandora/SophisticatedBackpacks] disconnect (Issue #66)




 
Exquisite Backpack?
 
I'll look into it it's cause by my litematica compat.

**Comment by york626** [comment]
extremely grateful

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
