### ISSUE TITLE
1.21.1 farmer delight and backpacks still don't together in fabric

### ISSUE THREAD

**Issue by JustAHuman8** [Salandora/SophisticatedBackpacks#69]
I tried to to see if they do work together today and it gave the Exit code 1, tried both mods with just themself and they work fine

**To Reproduce**
1. Have both mods in file
2. Click on play
3. Exit code 1 after it tries to open

**Expected behavior**
The game opens

yea :(

**Comment by Salandora** [comment]
Do you have a crash log for that?
Also which versions do you have of soph mods and farmers delight?

**Comment by Salandora** [comment]
Also what vversion of farmers delight do you have? I tested against 2.2.2 which worked fine for me, 2.1.10 did crash tho, so maybe it's just the need of an update?

**Comment by JustAHuman8** [comment]
OMG IT WAS JUST 2.1.10 THANK YOU SO MUCH

**Comment by Salandora** [comment]
No problem, enjoy playing.
I'll close this for now.
