### ISSUE TITLE
When placing a backpack with a stack over 64 in Creative makes it go down to 64

### ISSUE THREAD

**Issue by lieonlion** [Salandora/SophisticatedBackpacks#7]
**Describe the bug**
When placing a backpack with a stack over 64 in Creative makes it go down to 64.
Also any discord server I could join?

**To Reproduce**
1. Open backpack
2. Apply stack upgrade (any)
3. Add more than 64 items to 1 slot
4. Place down (in Creative)

**Expected behavior**
To keep the proper amount of items in the slots

**Versions**
Minecraft 1.20.1
Fabric - 0.15.10
Sophisticated Backpacks 3.19.4+mc1.20.1-build.39 (Modrinth)

**Comment by Salandora** [comment]
Will investigate this, not sure if it happens in the forge version too, I know that creative mode is a bit wonky with this mod.
About the Discord server yes you can join Peppersfly's discord server.  You can find the invite link through the curseforge page.
