### ISSUE TITLE
Incompatible with Farmer's Delight

### ISSUE THREAD

**Issue by IranMine123** [Salandora/SophisticatedBackpacks#70]
**Describe the bug**
Hello, somehow all the ported sophisticated mods are incomplete with other mods i have, and can't figure out what other mod is incomplete.
as log says, there are somethings wrong about "fabricators_of_create/porting-lib" (i think?... like i didn't even installed this mod)
here is the log: https://mclo.gs/uKJPLxw

**To Reproduce**
Just Running the game.

**Expected behavior**
Beautiful Main Menu

**Versions**
Minecraft: 1.21.1
Fabric Loader: 0.16.7
Sophisticated Core: 0.6.50.61
Sophisticated Backpacks: 3.20.19.51
Sophisticated Storage: 0.10.52.54

**Comment by Salandora** [comment]
Your farmers delight version is 2.1.10, can you update to a more recent version like 2.2.2.
I tested against that version and it works fine for me.

**Comment by IranMine123** [comment]
> Your farmers delight version is 2.1.10, can you update to a more recent version like 2.2.2. I tested against that version and it works fine for me.

it worked! TYSM

[Farmer's Delight Changelog](https://modrinth.com/mod/farmers-delight-refabricated/version/1.21.1-2.2.0)
