### ISSUE TITLE
Crashing when picking up item with certain addons

### ISSUE THREAD

**Issue by JustAHuman8** [Salandora/SophisticatedBackpacks#72]
On sophisticatedbackpacks version 1.21.1-3.20.19.51 

**To Reproduce**
1. Open backpack
2. Put Filter and or Magnet on with inception
3. Drop item
4. Crash beyond any other living thing will

**Expected behavior**
I pick up a item and dont crash

sorry for more bug reports :(

**Comment by Salandora** [comment]
I need a crash log for that. 
Also no worries about more bug reports.
I'm glad for every reported bug, because otherwise I might never find them.

**Comment by Salandora** [comment]
Found the issue, forgot to implement a function in the inception handler.
Will be fixed in the next version.

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
