### ISSUE TITLE
Incompatible with EMI

### ISSUE THREAD

**Issue by IranMine123** [Salandora/SophisticatedBackpacks#73]
***DISCLAIMER: This is a duplicate of https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/1226 issue. as the developer request, the issue is reposted on here.***

**Describe the bug**
Hello. There is a bug when trying to Recipe fill by [EMI](https://github.com/emilyploszaj/emi) using Sophisticated Backpack Crafting Upgrade (`sophisticatedcore:emi_fill_recipe`).
P3pp3rF1y said it's not fixed for fabric.
log of error: https://mclo.gs/jnayaJX
video:

https://github.com/user-attachments/assets/617d1500-e0bd-41d5-b45b-0f754d73c375

**To Reproduce**
1. Open backpack
2. Open Crafting Upgrade Grid
3. Open Recipe of any item on EMI (Clicking any item on EMI menu)
4. Using "+" (Recipe Fill) button
5. World Crashes

**Expected behavior**
fill the recipe on crafting upgrade grid successfully.

**Versions**
Minecraft: 1.21.1
Sophisticated Core: 0.6.50.61
Sophisticated Backpacks: 3.20.19.51
EMI: 1.1.18

**Comment by Salandora** [comment]
Can confirm this, interestingly it happened on the fence gate but not on like planks...
I'll investigate what's going on.

**Comment by IranMine123** [comment]
Really?
But I think I tried the other things too. Didn't worked

**Comment by Salandora** [comment]
I found the issue, not sure why it didn't happen on planks for me, from what I saw it should. Anyway will be fixed with the next update

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
