### ISSUE TITLE
Auto-smelting upgrade consumes all fuel

### ISSUE THREAD

**Issue by OkamiTia** [Salandora/SophisticatedBackpacks#77]
When using any smelting upgrade, adding fuel sources consumes them all 

1. Open backpack with any smelting upgrade
2. insert ore and any fuel type
3. consumes the whole stack and counts as only one

Screenshots:
![1](https://github.com/user-attachments/assets/0c276174-6acf-49a9-8677-72608f9537dd) ![2](https://github.com/user-attachments/assets/65c43c91-8bc7-4b2a-a551-0fa0a1163c77)
![3](https://github.com/user-attachments/assets/b2664464-413e-4e2c-962d-e1e7d90a275b)![4](https://github.com/user-attachments/assets/f1a1eca0-a097-41f4-9b49-d087282905ab)

Mods used:
fabric-api-0.108.0+1.21.1.jar
sophisticatedbackpacks-1.21.1-3.20.19.51.jar
sophisticatedcore-1.21.1-0.6.50.61.jar

**Comment by Salandora** [comment]
I can reproduce the issue, I wonder when and how that broke.

**Comment by MinerB4** [comment]
It's not just the Auto-smelting upgrade. I put in 43 Charcoal into my Furnace Upgrade, closed out of my backpack, then re-opened it only to find that I am now the proud owner of 0 Charcoal. The upgrade as a whole is pretty erratic too, sometimes the progress just twitches or it consumes two fuels at a time... then it gets hungrier.

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
