### ISSUE TITLE
Restock/Deposit upgrades fail to function

### ISSUE THREAD

**Issue by Demadunk** [Salandora/SophisticatedBackpacks#80]
Attempting to utilize both normal and advanced Restock/Deposit upgrades fail to work. It will always either say there are no available items to merge or not show any text at all.

**Comment by Salandora** [comment]
Which versions do you have?

**Comment by Demadunk** [comment]
Just in case this happens to be a mod compatability issue, here is my full modlist with the sophisticated mods in bold.

[Toffy's] HOOKS [1.00] 
Accessories [1.1.0-beta.16+1.21.1] 
Accessories Trinkets Compat Layer [3.10.0+beta.18] 
ActuallyHarvest [1.1.1.1] 
Adjusted Phantom Spawns [1.0.1-1.21] 
Advancement Frames [1.21-2.2.9] 
Alcohol-only [2.0.2] 
AlinLib [2.1.0-alpha.1+mc1.21] 
Alloy Forgery [2.4.1+1.21] 
Almanac [1.0.2] 
Amendments [1.21-1.2.19] 
Animal Armor Trims [2.0.0] 
Animal Feeding Trough [1.1.2+1.21.1] 
Apollo the Parrot [1.3] 
AppleSkin [3.0.6+mc1.21] 
Aquifer [0.0.3-1.21+] 
Architectury [13.0.8] 
Armadillo Brush Fix [1.2] 
Armor Nerf [2.2.0] 
Ars Elixirum [0.2.2] 
Artifacts [12.0.6] 
Arts & Crafts [1.2.0] 
Athena [4.0.1] 
Autochef's Delight [2.0.1+fabric] 
Awesome 3D Mace [1.1.0] 
Axolotl Buckets [1.2.0] 
Bad Packets [0.8.1] 
Balm [21.0.20] 
Bandanas [1.0] 
Bareback Horse Riding [2.2] 
Bartering Station [21.1.0] 
Beautiful Enchanted Books [1.0.0] 
Better Babies [0.7.13] 
Better Enchantment Order [1] 
Better Ladders [0.0.3.1.21] 
Better Statistics Screen [3.13.3+fabric-1.21] 
Better Tridents [21.1.0] 
better-boat-movement-2.2.3-1.21-fabric 
BetterThanMending [2.2.0] 
Bigger Better End Cities [1.21-1.1.0] 
BiomeParticleWeather [5.3.1] 
Block Breaker & Block Placer [1.0.2+1.21] 
Blåhaj [2.0.0] 
Book Scroll [1.0] 
Bucketable [3.3] 
Cake Chomps [10.0.1+1.21.1] 
Camera Utils [1.21.1-1.0.16] 
Care to Share [1.1+1.21] 
Carry On [2.2.2] 
Cherry On Top [1.1.1+1.21.1] 
Chested Companions [1.3.1] 
Chipped [4.0.2] 
Chiseled Bookshelf Visualizer [4.0] 
Chronograph [1.0.0] 
CICADA [0.9.1+1.21-1.21.1] 
CIT Resewn [1.2.2+1.21] 
ClickThrough Plus [3.0+1.21] 
Cloth Config v15 [15.0.140] 
Clumps [19.0.0.1] 
Collective [7.87] 
Collector's Album [2.1.4] 
Colourful Books [1.21-] 
Come back my villagers [1.2+1.21] 
Common Network [1.0.17-beta.2-1.21.1] 
Concurrent Chunk Management Engine [0.3.0+alpha.0.297+1.21.1] 
Configurable-2.2.2-fabric-yarn-1.21.1 
Configuration [3.1.0] 
Connectible Chains [2.4.2+1.21.1] 
Copper Hopper [0.10.0+1.21.1] 
CopperGratesBubbleThru [1.1+1.21] 
CoroUtil [1.21.0-1.3.7] 
CraftableCapes [1.1.1] 
CraftTweaker [21.0.7] 
Crate Delight [24.11.06-1.21-fabric] 
Crawl [0.13.0] 
CreativeCore [2.12.22] 
Crops Love Rain [2.1.1] 
Crying Portals [2.8] 
Cut Through [21.1.0] 
Darceno's Minecarts [1.4] 
DeathQuotes [3.3] 
Deeper and Darker [1.3.2.1] 
Defense [1.21-0.4.1] 
Deslabification [1.1.0+1.21+fabric] 
DetailedMobGriefing [0.8.4] 
Diagonal Fences [21.1.0] 
Diagonal Walls [21.1.0] 
Diagonal Windows [21.1.0] 
DimensionalTrialChambers [1.0.2] 
Disable Custom Worlds Advice [6.0] 
Do a Barrel Roll [3.7.2] 
Dramatic Doors [1.21.1-3.2.7] 
Dumpling's Delight Rewrapped [1.21-1.2.0a+fabric] 
Durability Tooltip [1.1.5] 
Dyed Bundles [1.0] 
Dynamic FPS [3.7.6] 
Dynamic Lights [1.8.3+mod] 
e4mc [5.2.1] 
Easy Anvils [21.1.0] 
Easy Magic [21.1.0] 
Echo Chest [21.1.0] 
Economical Villager Trading [1.3.1] 
EffectTimerPlus [2.2.3+1.21] 
Elytra Trims [3.5.4] 
Elytra Trims Extensions [2.2.1] 
EMI [1.1.18+1.21.1+fabric] 
EMI Enchanting [0.1.2+1.21] 
EMI Loot [0.7.4+1.21+fabric] 
Enchantable Horse Armor [1.0.0] 
Enchantable Horse Armor [1.0.0] 
Enchantable Wolf Armor [1.0.0] 
Enchanted Vertical Slabs [2.3.1] 
Enhanced Cats [0.6] 
Enhanced Mob Spawners [1.2.8] 
Entity Model Features [2.2.6] 
Entity Texture Features [6.2.7] 
EntityCulling [1.7.1] 
Excessive Building [3.3.7] 
Expanded Axe Enchanting [1.0.11] 
Expanded Bow Enchanting [1.1.2] 
Expanded Crossbow Enchanting [1.0.2] 
Expanded Trident Enchanting [1.0.11] 
Expedition Essentials [1.0.0] 
Explorer's Compass [1.21-2.2.5-fabric] 
Explorify [1.6.2] 
Explosive Enhancement [1.2.3-1.21.0] 
Fabric API [0.108.0+1.21.1] 
Fabric Language Kotlin [1.12.3+kotlin.2.0.21] 
Falling Leaves [1.16.2] 
FallingTree [1.21.1.2] 
Farmer's Delight [1.21.1-2.2.2+refabricated] 
FarmersStructures [1.0.0] 
FerriteCore [7.0.2-hotfix] 
FindMe [3.3.1] 
Fishingreal [1.21-1.9.0] 
Flow [2.1.2+1.21] 
Flower Patch [7.0.1] 
Followers Teleport Too [2.6] 
Forge Config API Port [21.1.2] 
Forgiveness [1.5.0] 
Forgiving Void [21.1.1] 
Forkcart [1.21-1.1.0] 
Fragmentum [0.0.13] 
Friends & Foes [3.0.6] 
Fusion [1.1.1] 
Fzzy Config [0.5.6+1.21] 
Gardens of the Dead [5.0.0] 
GeckoLib 4 [4.7] 
Geophilic [3.1.4] 
Get It Together, Drops! [fabric-1.21-1.3.1] 
GlitchCore [2.1.0.0] 
Glow Ink Plus Mod [1.2] 
Grass Overhaul [1.0.0] 
Grind Enchantments [3.2.2+1.21-rc1] 
Guarding [1.21.1-2.7.4] 
GuardVillagers [2.1.2-1.21] 
Handcrafted [4.0.2] 
Head Index [1.1.7] 
Hearths [1.0.1] 
HopoBetterMineshaft [1.2.8] 
HopoBetterRuinedPortals [1.4.4] 
HopoBetterUnderwaterRuins [1.2.1] 
HorseBuff [2.1.8] 
Horseshoes [1.2.4] 
Hungrier [1.2] 
iChunUtil [1.0.0] 
idwtialsimmoedm [0.3.2+1.21] 
Incapacitated [1.9.1] 
Indium [1.0.35+mc1.21] 
IndyPets - Independent Pets [1.4.3] 
Infinite Dragon Eggs [1.0.0] 
Inventory Profiles Next [2.0.10] 
Inventory Totem [3.3] 
Ipla [1.3] 
Iris [1.8.0-beta.8+mc1.21.1] 
Items Displayed [1.3] 
Jump Over Fences [1.6.0] 
Just Mob Heads [8.3] 
Just More Cakes! [1.19.2] 
Kaffee's Dual Ride [1.1.0] 
Kiwi Library [15.1.2+fabric] 
Lavender [0.1.14+1.21] 
Leaves Be Gone [21.1.0] 
Legacies and Legends [1.21.1-v1.4.0] 
Let Me Despawn [1.4.4] 
Let Sleeping Dogs Lie [1.3.0] 
libIPN [6.1.1] 
Librarian's Balance [3.5] 
Linkart [5.4.5-1.20.6-build.29] 
Lithium [0.14.0-snapshot+mc1.21.1-build.88] 
Llama Steeds [2024.08.08] 
Loot Journal [4.0.1] 
Lootr [1.21-1.10.34.86] 
Luki's Crazy Chambers [1.0] 
MaLiLib [0.21.1] 
Minecord [2.1.0+1.21] 
Minekea [6.1.1] 
Mod Menu [11.0.3] 
ModernFix [5.19.5+mc1.21.1]
Monkey Config [0.1.2+1.21] 
MonoLib [1.4.1] 
Moonlight Lib [1.21-2.17.1] 
More Armor Trims [1.4.1-1.21] 
More Axolotl Variants API [1.2.1] 
More Axolotl Variants Mod [1.3.0] 
More Brushes [1.3] 
More Cartography Tables [1.6.0] 
More Cartography Tables [1.7.0] 
More Cartography Tables [1.7.1] 
More Chiseled Bookshelf Variants [1.6.2] 
More Composter Variants [1.7.0] 
More Crafter Variants [1.0.0] 
More Crafting Tables [1.2.8] 
More Delight [24.09.27-1.21-fabric] 
More Feeding Trough Variants [1.0.1] 
More Fletching Tables [1.6.1] 
More Fletching Tables [1.7.0] 
More Furnace Variants [1.0.3] 
More Grindstone Variants [1.0.4] 
More Jukebox/Noteblock Variants [1.0.2] 
More Lectern Variants [1.7.1] 
More Lectern Variants [1.8.0] 
More Lectern Variants [1.8.1] 
More Loom Variants [1.1.0] 
More Smithing Tables [1.2.0] 
More Smoker Variants [1.2.1] 
Mouse Tweaks [2.26] 
MRU-1.0.4-1.21-fabric 
Music Notification [2.1.0] 
Music Sync [1.3] 
Mythic Metals [0.20.2+1.21] 
Naturally Charged Creepers [3.5] 
Nature's Compass [1.21-2.2.6-fabric] 
Necronomicon [1.6.0] 
Nemo's Blooming Blossom [1.3-1.21.1] 
Nether Depths Upgrade [fabric-3.1.8-1.21] 
NetherPortalFix [21.1.1] 
Network Protocol Disconnect [1.1.0+1.21] 
Noisium [2.3.0+mc1.21-1.21.1] 
Not Enough Crashes [4.4.8+1.21] 
Not Enough Recipe Book [0.4.1] 
NotEnoughAnimations [1.8.1] 
Nox: Renoxed [2.7.2+1.21] 
Nullscape [1.2.9] 
Nyf's Quivers [2.0.3] 
Observable [5.4.3] 
Ocean's Delight [fdrf-fabric-1.0.2-1.21] 
OctoLib [0.4.2] 
Open Parties and Claims [0.23.2] 
OrthoCamera [0.1.8+1.21] 
Our Villager Discounts [1.21+build.0] 
oωo [0.12.15+1.21] 
Particle Tweaks [2.0-mc1.21.1] 
Party Flame [1.0.0-1.21] 
Passable Foliage [9.1.2+fabric] 
Peek [1.21.1-1.3.6] 
PerPlayerWanderingTraders [1.0.2+1.20.6] 
Persistent Parrots [1.0] 
Pets Not Friendly Fire [1.0.2] 
Philip`s Ruins [1.21.1] 
Placeholder API [2.4.1+1.21] 
Player Animator [2.0.0-alpha1+1.21] 
PneumonoCore [1.1.6] 
Polymorph [1.0.6+1.21.1] 
Presence Footsteps [1.10.0+1.21] 
Psittacine [1.0.0] 
Public Ender Chest [1.1.0] 
Pumpkin Pie Delight [1.0.1+1.21] 
Pure Discs - Trails & Tales [2.0.1] 
Pure Discs - Tricky Trials [2.0.0] 
Puzzles Lib [21.1.22] 
Quad [1.2.9] 
Resourceful Lib [3.0.11] 
Respawnable Pets [1.21-r2] 
Respawning Shulkers [4.0] 
Scaffolding Drops Nearby [3.3] 
Scarecrows' Territory [1.1.11+a] 
Scribble [1.4.1-beta] 
Scriptor [1.3.5-1.21] 
Seed Delight [0.1] 
Sensible Sleepiness [0.0.4-1.21] 
SereneSeasons [10.1.0.1] 
Shifting Wares [3.0.0+1.21.3] 
Signed Paintings [1.1.1-mc1.21] 
Simple Copper Pipes [2.0.3] 
Simple Fog Control [1.6.0] 
Simple Voice Chat [1.21.1-2.5.25] 
Sketch [1.21.1-1.2.1] 
SkinShuffle [2.2.2+1.21] 
Smarter Farmers [1.21-2.1.5] 
Smeltable Ore Blocks [1.21-1.0] 
Smoke Signals [1.1] 
Smooth Scroll [2.2.0] 
Snow! Real Magic! [11.0.12+fabric] 
SnowyLeavesPlus [0.1.12] 
Sodium [0.6.0-beta.4+mc1.21.1] 
**Sophisticated Backpacks [1.21.1-3.20.19.51] 
Sophisticated Core [1.21.1-0.6.50.61] 
Sophisticated Storage [1.21.1-0.10.52.54]** 
Sound Physics Remastered [1.21.1-1.4.6] 
Sounds-2.2.0-1.21-fabric 
spark [1.10.109] 
Stack Refill [4.5] 
Storage Delight [24.09.11-1.21-fabric] 
Styled Nicknames [1.6.0+1.21] 
SuperMartijn642's Config Library [1.1.8] 
SuperMartijn642's Core Lib [1.1.17+h] 
Tax Free Levels [1.4.1] 
TCD Commons API [3.12.4+fabric-1.21] 
Terralith [2.5.6] 
Texturized Particles [1.0.1+1.21] 
Thaumon [2.3.0+1.21] 
The Bumblezone - Fabric [7.7.7+1.21.1-fabric] 
Things [0.4.2+1.21] 
This Rocks! [1.8.2] 
throw [1.0.0] 
Tidal Towns [1.3.3] 
Tide [1.3.4] 
TimeStacker [1.2.0] 
Tinted Campfires [1.0.0] 
TNT Breaks Bedrock [3.4] 
Trade Cycling [1.21.1-1.0.15] 
Trailier Tales [1.0.5+1.21.1] 
Trenzalore [6.1.1] 
Trickster [2.0.0-beta.3] 
Trowel [1.4.0] 
TT20 [0.7.0] 
Ube's Delight [0.2.3] 
Universal Bone Meal [21.1.0] 
Universal Sawmill [1.21-1.5.9] 
Unloaded Activity [0.6.4] 
Untitled Duck Mod [0.7.0] 
Valhelsia Core [1.1.3] 
Valhelsia Furniture [1.1.0] 
Very Many Players [0.2.0+beta.7.169+1.21.1] 
ViaFabric [0.4.15+84-main] 
Villager Hats [1.7.2+1.21] 
Villager Trading Plus [1.1+1.21] 
Visible Traders [0.0.6] 
Visual Workbench [21.1.0] 
Voice Chat Interaction [1.21.1-1.0.8] 
Wakes [0.3.0+1.21.1] 
WaterFrames [2.1.7b] 
WaterMedia [2.1.3] 
WaveyCapes [1.4.12] 
Waystones [21.1.5] 
Weaker Spiderwebs [3.7] 
What Are They Up To [1.21.0-1.1.3] 
When Dungeons Arise [2.1.60] 
WI Zoom [1.5-MC1.21.1] 
Wilder Wild [3.0.8-mc1.21.1] 
wthit [12.4.3] 
Xaero's Minimap [24.2.1] 
Xaero's World Map [1.39.0] 
Yeetus Experimentus [87.0.0] 
You're in Grave Danger [2.4.11] 
Zombify [0.1.4]

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
