### ISSUE TITLE
Experience in Tank upgrades can be deposited but not withdrawn

### ISSUE THREAD

**Issue by Demadunk** [Salandora/SophisticatedBackpacks#84]
Newest versions of all three mods,
Tanks with experience shows the amount of experience in Milibuckets instead of XP level,

Experience can be siphoned off of your person the way the Exp. pump functions but it does not repair items with mending or allow you to retrieve XP from the tank via the pump settings.

![2024-12-05_23 05 43](https://github.com/user-attachments/assets/e7e6f805-1566-47a0-89b4-147379dc0380)

**Comment by york626** [comment]
I've also encountered this situation and can't fix the tool, which should be a bug

**Comment by Salandora** [comment]
Yeah I think I know what happened here...
fabric added the standardized experience tag and so I switched to using that of course.
Completely forgetting that I still have to add the experience fluid to the tag and therefore removed that code... 

Should be an easy fix once I'm home.
Will double check mending too.

**Comment by Salandora** [comment]
Released a new SophisticatedCore version that should fix the issue.
