### ISSUE TITLE
backpack deleting itself

### ISSUE THREAD

**Issue by D0CT3ER** [Salandora/SophisticatedBackpacks#86]
When using a backpack with the "Advanced refill upgrade" and middle clicking a block to pick it from the backpack while the backpack is in your hand, it deletes the backpack. Kinda...
I noticed that if you are holding an item while middle clicking it sends the item to the bag and grabs the middle clicked block... but if you do it with the backpack in your hand, it send the backpack into itself... deleting it.

**To Reproduce**
1. have a backpack with "advanced refill upgrade" enabled
2. have block of choice placed and rest in backpack. NOT IN INVENTORY
3. middle click placed block while the backpack is your held item
4. backpack gone...

**Versions**
I am playing fabric version Beta release sophisticatedbackpacks-3.19.5+mc1.20.1-SNAPSHOT-build.104.jar
I am aware that this is a beta and an older version, but it is the only version compatible with the most recent  full release of  jei.

**Comment by Salandora** [comment]
hmm this sounds very similar to the issue I had with the tool swapper. 
I'll look into it.

**Comment by Salandora** [comment]
Okay so the issue was fixed in a newer version of sophisticated backpacks.
I also checked with JEI 15.20.0.105 (most recent version on curseforge) just now and it works just fine.
So the only thing you can do is update.
