### ISSUE TITLE
Server crashes when backpack is loaded chatGBT says someone sophisticated backpack has a negative FE value

### ISSUE THREAD

**Issue by Nintendoboi22** [Salandora/SophisticatedBackpacks#88]
https://api.mclo.gs/1/raw/bNJkIgZ

**Describe the bug**
My friend has a create modpack minecraft server and this is the second time someones backpack has gotten a negative FE value, this causes the server to crash every time I join or the chunk with the backpack inside is loaded

**To Reproduce**
I do not know how. This just happened when I was running around.

**Expected behavior**
Server not to crash

**Versions**
modrinth
Sophisticated Backpacks (Unoffical Fabric port)
by Salandora
1.20.1-3.20.17.1.60

**Comment by Salandora** [comment]
This is part of #87 it's fixed in dev but a bug with sophisticated storage controller blocks that affects sophisticated core holds me back from releasing it.
Once I have that bug sorted out I'll release new versions.

**Comment by Salandora** [comment]
New release of Sophisticated Core is out and should fix this.
