### ISSUE TITLE
Crash when opening backpack settings

### ISSUE THREAD

**Issue by JL-math** [Salandora/SophisticatedBackpacks#90]
Version: 1.20.4
Whenever the settings tab of the backpack is opened, the settings menu displays for a frame and the server then crashes instantly. This does not occur in singleplayer

The same crash also occurs whit the sophisticatted storage barrels (only tested limitted barrel 1 however)

1. Join a server with sophisticated backpacks installed
2. Open a backpack
3. Click the settings tab (the one whit the gear)
4. Server crashes

**Expected behavior**
The settings menu opens and the server does not crash

**Versions**
Fabric API 0.97.2+1.20.4
Sophisticated Backpacks 1.20.4-3.20.6.41
Sophisticated Core 1.20.4-0.6.26.79
Sophisticated Storage 1.20.4-0.10.26.33

**Crashlog**
[crash-2024-12-20_22.43.21-server.txt](https://github.com/user-attachments/files/18216203/crash-2024-12-20_22.43.21-server.txt)

**Comment by Salandora** [comment]
I can confirm the issue just not sure what is causing it.
I'll look into it

**Comment by Salandora** [comment]
Just released a new version, that fixes this.

**Comment by Salandora** [comment]
Sophisticated Core
