### ISSUE TITLE
"Transfer matching to backpack" Doesnt work

### ISSUE THREAD

**Issue by programaus** [Salandora/SophisticatedBackpacks#91]
Simply doesnt do anything. (Transfer matching to inventory works perfectly though)
https://streamable.com/3wpe3h
![image](https://github.com/user-attachments/assets/cb352280-8c3f-4af7-a6fd-290e9035544e)

**Comment by Salandora** [comment]
Update sophisticated core I release a fix for that yesterday. :)

**Comment by programaus** [comment]
yeah I cut off the update button there 😭 thanks though
