### ISSUE TITLE
Advanced Liquid Pump BUG

### ISSUE THREAD

**Issue by york626** [Salandora/SophisticatedBackpacks#94]
**Description Bug**
After updating to sophisticatedcore-1.21.1-0.7.14.1.91
The advanced liquid pump interacts with the hand-held vessel and cannot be used

English is not good and the description is not clear

**Expected Behavior**
The bucket will be filled with a bucket of water

**Screenshot**
![2024-12-29_09 42 16](https://github.com/user-attachments/assets/bfdd04bb-ea54-4924-a760-7af157748e83)

The functions marked in the figure cannot be used normally

**Version**
fabric-api-0.110.0+1.21.1
sophisticatedcore-1.21.1-0.7.14.1.91
sophisticatedbackpacks-1.21.1-3.20.26.1.61

**Comment by Salandora** [comment]
Can confirm this bug. Not sure why and how it broke this time....

**Comment by Salandora** [comment]
Found the issue and will release a fix soon.

**Comment by york626** [comment]
@Salandora extremely grateful，Fixed pump upgrade interaction with buckets

After the update, there are new problems and bugs, and the advanced liquid pump is full of experience

![2024-12-31_09 27 22](https://github.com/user-attachments/assets/a8baf36d-20fb-4ee0-8769-3f583637db15)

Version
fabric-api-0.114.0+1.21.1
sophisticatedcore-1.21.1-0.7.14.2.101
sophisticatedbackpacks-1.21.1-3.20.26.2.69

**Comment by Salandora** [comment]
What exactly are the new bugs? 
I just tested the pump upgrade and I can't get it to fill the tank with experience unless I take the Bucket of Experience.
Please provide step by step instructions to reproduce your issue. 

Also keep in mind if you are in creative the interaction with buckets is different then in survival.
In creative the bucket will not be emptied, while it will be emptied in survival.

**Comment by york626** [comment]
> What exactly are the new bugs? I just tested the pump upgrade and I can't get it to fill the tank with experience unless I take the Bucket of Experience. Please provide step by step instructions to reproduce your issue.
> 
> Also keep in mind if you are in creative the interaction with buckets is different then in survival. In creative the bucket will not be emptied, while it will be emptied in survival.

Sorry for my issue, everything works fine at the moment

**Comment by Salandora** [comment]
No worries, enjoy the mod and ket me know if you find anything else :)
